### PR TITLE
 rescue NameError 

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
Ruby/Redmine combinations need updating for all the builds to succeed.

**Comment by mmoll** [comment]
@jkraemer WDYT?

**Comment by jkraemer** [comment]
not a fan of introducing these Rails version checks in the test cases. I'd rather drop support for Redmine < 4 in the master branch. Under what circumstances did you get that NameError?

**Comment by mmoll** [comment]
@jkraemer See the test failures in master. Also, according to the issue, people seem to get this in the real app.

**Comment by mmoll** [comment]
For the tests, give me a list of Redmine and Ruby releases that should get tested  and i'll push it here. :+1:

**Pull request closed without merging**
